name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  marine-rs-sdk-test:
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}
