name: Run tests with workflow_call

on:
  workflow_call:
    inputs:
      fluence-app-service-version:
        description: "fluence-app-service version"
        type: string

env:
  RUST_TEST_THREADS: 1

jobs:
  marine-rs-sdk-test:
    name: "Run tests"
    runs-on: builder

    steps:
      - name: Checkout to marine-rs-sdk-test
        uses: actions/checkout@v3
        with:
          repository: "fluencelabs/marine-rs-sdk-test"

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set fluence-app-service version from branch
        if: inputs.fluence-app-service-version != ''
        uses: fluencelabs/github-actions/cargo-set-dependency@main
        with:
          package: fluence-app-service
          version: ${{ inputs.fluence-app-service-version }}

      - name: debug
        run: dasel -f Cargo.lock -p toml 'package.(name=fluence-app-service).source' -m

      - name: Run cargo build
        run: cargo build

      - name: Run cargo check
        run: cargo check -v --all-features

      - name: Run cargo test
        run: cargo test --release --all-features --no-fail-fast

      - name: Run cargo clippy
        run: cargo clippy -Z unstable-options --all

      - name: Run rustfmt
        uses: actions-rust-lang/rustfmt@v1
