name: Run tests with workflow_call

on:
  workflow_call:
    inputs:
      marine-runtime-version:
        description: "marine-runtime version"
        type: string

env:
  RUST_TEST_THREADS: 1

jobs:
  marine-rs-sdk-test:
    name: "Run tests"
    runs-on: builder

    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set marine-runtime version from branch
        if: inputs.marine-runtime-version != ''
        uses: fluencelabs/github-actions/cargo-set-dependency@main
        with:
          package: marine-runtime
          version: ${{ inputs.marine-runtime-version }}

      - name: Run cargo build
        run: cargo build

      - name: Run cargo check
        run: cargo check -v --all-features

      - name: Run cargo test
        run: cargo test --release --all-features --no-fail-fast

      - name: Run cargo clippy
        run: cargo clippy -Z unstable-options --all

      - name: Run rustfmt
        uses: actions-rust-lang/rustfmt@v1
